

aca_shop_homepage:
    path: /
    defaults: { _controller: AcaShopBundle:Default:index }
    methods: [GET, POST]

#aca_shop_homepage:
#    path:     /hello/{name}/{age} #try acashop.vm/hello/simon => will show hello simon! {} means variable here
#    defaults: { _controller: AcaShopBundle:Default:index } #after reroute from above line, it will go to the controller

#aca_login_route:
#    path: /login_form
#    defaults: { _controller: AcaShopBundle:Login:loginForm } #loginForm method
#    methods: [GET, POST]


#aca_login_handler:
#    path: /process_login
#    defaults: { _controller: AcaShopBundle:Default:processLogin } #Default is Class = DefaultController.php
#    methods: [GET, POST]                                                              #and processLogin is method (required to make processLoginAction

#aca_logout_route:
#    path: /logout
#    defaults: { _controller: AcaShopBundle:Login:logout } #logoutAction method
#    methods: [POST]

#aca_login:
#    path: /
#    defaults: { _controller: AcaShopBundle:Login:login }
#    methods: [POST]

aca_logout_route:
    path: /logout
    defaults: { _controller: AcaShopBundle:Default:logout } #logoutAction method
    methods: [POST]

aca_registration:
    path: /register
    defaults: { _controller: AcaShopBundle:Registration:register }
    methods: [GET, POST]

aca_toHome:
    path: /toHome
    defaults: { _controller: AcaShopBundle:Registration:toHome }
    methods: [POST]

aca_products:
    path: /products
    defaults: { _controller: AcaShopBundle:Product:showAll }
    methods: [GET] #Get-only indicates that it's contents only page

aca_single_products:
    path: /products/{category}/{slug}
    defaults: { _controller: AcaShopBundle:Product:showOne }
    methods: [GET]