services:
#    aca_shop.example:
#        class: Aca\Bundle\ShopBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    acadb:                                  #give service a name
      class: Simplon\Mysql\Mysql                  #class name
      arguments: [%database_host%, %database_user%, %database_password%, %database_name%]   #coming from config (packagist.org simplon)


    cart:
      class: Aca\Bundle\ShopBundle\Service\CartService
      arguments: [@acadb, @session]

    order:
      class: Aca\Bundle\ShopBundle\Service\OrderService
      arguments: [@acadb, @session, @cart]
